#!/usr/bin/env python3
"""Write Llama-ready copies of the low-stakes training CSVs without Qwen <think> tags."""

from __future__ import annotations

import csv
import hashlib
import json
import re
from pathlib import Path


REPO_DIR = Path(__file__).resolve().parent
PROJECT_DIR = REPO_DIR.parent
REPO_OUTPUT_DIR = REPO_DIR / "data" / "LLAMA_READY_NO_THINK_TAGS"
LOCAL_OUTPUT_DIR = PROJECT_DIR / "LLAMA_READY_NO_THINK_TAGS_low_stakes_training_sets"
TEXT_COLUMNS = ("chosen_full", "rejected_full")
THINK_WRAPPED_WITH_ANSWER_RE = re.compile(
    r"(?s)^\s*<think>\s*(.*?)\s*</think>\s*(\{.*\})\s*$"
)
SOURCE_SPECS = [
    {
        "source_subpath": "CoT-training/2026_03_22_low_stakes_training_set_1000_situations_with_CoTs.csv",
        "output_name": "LLAMA_READY_2026_03_22_low_stakes_training_set_1000_situations_CoTs_no_think_tags.csv",
    },
    {
        "source_subpath": "2026_03_22_low_stakes_training_set_600_situations_with_CoTs_lin_only.csv",
        "output_name": "LLAMA_READY_2026_03_22_low_stakes_training_set_600_situations_CoTs_no_think_tags_lin_only.csv",
    },
    {
        "source_subpath": "CoT-training/combined 2026_04_13_modified.csv",
        "output_name": "LLAMA_READY_combined_2026_04_13_modified_no_think_tags.csv",
    },
]


def strip_qwen_think_tags(text: str) -> str:
    """Remove outer Qwen-style think tags while preserving the reasoning and final answer JSON."""
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    if "<think>" not in normalized and "</think>" not in normalized:
        return normalized

    match = THINK_WRAPPED_WITH_ANSWER_RE.match(normalized)
    if match is None:
        raise ValueError(
            "Expected a '<think> ... </think> {\"answer\":...}' structure, but found a different shape."
        )

    reasoning = match.group(1).strip("\n")
    answer_json = match.group(2).strip()
    if reasoning:
        return f"{reasoning}\n\n{answer_json}"
    return answer_json


def _read_csv(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        fieldnames = list(reader.fieldnames or [])
        rows = [dict(row) for row in reader]
    return fieldnames, rows


def _write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def transform_rows(rows: list[dict[str, str]]) -> tuple[list[dict[str, str]], dict[str, int]]:
    out_rows: list[dict[str, str]] = []
    changed_cells = 0
    rows_with_changes = 0
    cells_checked = 0

    for row in rows:
        out_row = dict(row)
        row_changed = False
        for column in TEXT_COLUMNS:
            if column not in row:
                continue
            value = out_row.get(column, "")
            if not isinstance(value, str):
                continue
            cells_checked += 1
            new_value = strip_qwen_think_tags(value)
            if new_value != value:
                changed_cells += 1
                row_changed = True
            if "<think>" in new_value or "</think>" in new_value:
                raise ValueError(f"Think tags survived in column {column!r}.")
            out_row[column] = new_value
        if row_changed:
            rows_with_changes += 1
        out_rows.append(out_row)

    return out_rows, {
        "cells_checked": cells_checked,
        "changed_cells": changed_cells,
        "rows_with_changes": rows_with_changes,
    }


def write_readme(output_dir: Path, manifest_rows: list[dict[str, object]]) -> None:
    lines = [
        "# Llama-ready low-stakes training copies",
        "",
        "These CSVs are copies of the current March 22 low-stakes training sets with the Qwen-specific `<think>` and `</think>` tags removed from `chosen_full` and `rejected_full`.",
        "",
        "Why these exist:",
        "- The reasoning text and final answer JSON are preserved.",
        "- Only the outer `<think>` wrappers were removed.",
        "- These copies are meant for Llama-family training runs where those Qwen-specific tags are undesirable.",
        "",
        "Generated by:",
        "- `make_llama_no_think_training_copies.py`",
        "",
        "Files:",
    ]
    for row in manifest_rows:
        lines.append(f"- `{row['output_name']}` from `{row['source_name']}`")
    lines.append("")
    readme_path = output_dir / "README.md"
    readme_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    manifest_rows: list[dict[str, object]] = []
    REPO_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    LOCAL_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for spec in SOURCE_SPECS:
        source_path = REPO_DIR / "data" / spec["source_subpath"]
        source_name = source_path.name
        fieldnames, rows = _read_csv(source_path)
        transformed_rows, stats = transform_rows(rows)

        for output_dir in (REPO_OUTPUT_DIR, LOCAL_OUTPUT_DIR):
            output_path = output_dir / spec["output_name"]
            _write_csv(output_path, fieldnames, transformed_rows)

        repo_output_path = REPO_OUTPUT_DIR / spec["output_name"]
        local_output_path = LOCAL_OUTPUT_DIR / spec["output_name"]
        manifest_rows.append(
            {
                "source_name": source_name,
                "source_subpath": spec["source_subpath"],
                "output_name": spec["output_name"],
                "num_rows": len(rows),
                **stats,
                "repo_output_path": str(repo_output_path),
                "repo_output_sha256": _sha256(repo_output_path),
                "local_output_path": str(local_output_path),
                "local_output_sha256": _sha256(local_output_path),
            }
        )

    manifest = {
        "script": str(Path(__file__).resolve()),
        "repo_output_dir": str(REPO_OUTPUT_DIR),
        "local_output_dir": str(LOCAL_OUTPUT_DIR),
        "files": manifest_rows,
    }

    for output_dir in (REPO_OUTPUT_DIR, LOCAL_OUTPUT_DIR):
        (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        write_readme(output_dir, manifest_rows)

    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
