#!/usr/bin/env python3
"""Write no-think-tag copies of the low-stakes training CSVs."""

from __future__ import annotations

import csv
import re
from pathlib import Path


REPO_DIR = Path(__file__).resolve().parent
REPO_OUTPUT_DIR = REPO_DIR / "data" / "NO_THINK_TAGS"
TEXT_COLUMNS = ("chosen_full", "rejected_full")
THINK_WRAPPED_WITH_ANSWER_RE = re.compile(
    r"(?s)^\s*<think>\s*(.*?)\s*</think>\s*(\{.*\})\s*$"
)
SOURCE_SPECS = [
    {
        "source_name": "2026_03_22_low_stakes_training_set_1000_situations_with_CoTs.csv",
        "output_name": "2026_03_22_low_stakes_training_set_1000_situations_CoTs_no_think_tags.csv",
    },
    {
        "source_name": "2026_04_13_tie_training_modified_CoTs.csv",
        "output_name": "2026_04_13_tie_training_modified_CoTs_no_think_tags.csv",
    },
]


def strip_qwen_think_tags(text: str) -> str:
    """Remove outer Qwen-style think tags while preserving the reasoning and final answer JSON."""
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    if "<think>" not in normalized and "</think>" not in normalized:
        return normalized

    match = THINK_WRAPPED_WITH_ANSWER_RE.match(normalized)
    if match is None:
        raise ValueError(
            "Expected a '<think> ... </think> {\"answer\":...}' structure, but found a different shape."
        )

    reasoning = match.group(1).strip("\n")
    answer_json = match.group(2).strip()
    if reasoning:
        return f"{reasoning}\n\n{answer_json}"
    return answer_json


def _read_csv(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        fieldnames = list(reader.fieldnames or [])
        rows = [dict(row) for row in reader]
    return fieldnames, rows


def _write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def transform_rows(rows: list[dict[str, str]]) -> tuple[list[dict[str, str]], dict[str, int]]:
    out_rows: list[dict[str, str]] = []
    changed_cells = 0
    rows_with_changes = 0
    cells_checked = 0

    for row in rows:
        out_row = dict(row)
        row_changed = False
        for column in TEXT_COLUMNS:
            if column not in out_row:
                continue
            value = out_row.get(column, "")
            if not isinstance(value, str):
                continue
            cells_checked += 1
            new_value = strip_qwen_think_tags(value)
            if new_value != value:
                changed_cells += 1
                row_changed = True
            if "<think>" in new_value or "</think>" in new_value:
                raise ValueError(f"Think tags survived in column {column!r}.")
            out_row[column] = new_value
        if row_changed:
            rows_with_changes += 1
        out_rows.append(out_row)

    return out_rows, {
        "cells_checked": cells_checked,
        "changed_cells": changed_cells,
        "rows_with_changes": rows_with_changes,
    }


def write_readme(output_dir: Path, manifest_rows: list[dict[str, object]]) -> None:
    lines = [
        "# No-think-tag low-stakes copies",
        "",
        "These CSVs are copies of the current low-stakes training sets with the Qwen-specific `<think>` and `</think>` tags removed from `chosen_full` and `rejected_full` where present.",
        "",
        "Why these exist:",
        "- The reasoning text and final answer JSON are preserved.",
        "- Only the outer `<think>` wrappers were removed.",
        "- These copies are used for Llama and Gemma runs, which do not use the Qwen-style think tags.",
        "",
        "Generated by:",
        "- `make_no_think_tag_training_copies.py`",
        "",
        "Files:",
    ]
    for row in manifest_rows:
        lines.append(f"- `{row['output_name']}` from `{row['source_name']}`")
    lines.append("")
    readme_path = output_dir / "README.md"
    readme_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    manifest_rows: list[dict[str, object]] = []
    REPO_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for spec in SOURCE_SPECS:
        source_path = REPO_DIR / "data" / spec["source_name"]
        fieldnames, rows = _read_csv(source_path)
        transformed_rows, stats = transform_rows(rows)

        output_path = REPO_OUTPUT_DIR / spec["output_name"]
        _write_csv(output_path, fieldnames, transformed_rows)

        manifest_rows.append(
            {
                "source_name": spec["source_name"],
                "output_name": spec["output_name"],
                "num_rows": len(rows),
                **stats,
            }
        )

    write_readme(REPO_OUTPUT_DIR, manifest_rows)
    print(f"Wrote {len(manifest_rows)} no-think-tag CSVs to {REPO_OUTPUT_DIR}")


if __name__ == "__main__":
    main()
